name: Build SEB Windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore SafeExamBrowser.sln

      - name: Build solution
        run: msbuild SafeExamBrowser.sln /p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SEB-Binaries
          path: |
            **/bin/Release/**/*.exe
            **/bin/Release/**/*.dll
